// Server entrypoint. See CONTRACTS.md §H. Loads env, opens the store, loads users,
// wires the real (or partially-available) core deps, and listens.
import { existsSync, readFileSync } from 'node:fs';
import { openStore } from '../adapters/store/index.js';
import { createAudit } from '../core/audit.js';
import { log } from '../core/log.js';
import { normalizeUsers } from './auth.js';
import { createApp } from './app.js';
import { createBooksClient, loadBooksConfig } from '../books/index.js';

/**
 * Users file shape (CONTRACTS.md §H): `{ users: [{ id, role, branches, token_sha256 }] }`
 * or a bare array of the same objects. Generated by a separate workstream
 * (config/users.json / config/users.example.json); never invent tokens here.
 */
function loadUsers(path) {
  if (!path || !existsSync(path)) {
    log('warn', 'users_config_not_found', { path });
    return [];
  }
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    const users = normalizeUsers(Array.isArray(raw) ? raw : raw.users ?? []);
    log('info', 'users_config_loaded', {
      path, count: users.length,
      bots: users.filter((u) => u.principal_type === 'bot').map((u) => u.id),
    });
    return users;
  } catch (err) {
    // Fail closed: a malformed or contradictory principal list (e.g. a bot declared as a
    // human operator) must stop the server rather than start with weaker authorization.
    log('error', 'users_config_invalid', { path, error: String(err?.message ?? err) });
    process.exit(1);
  }
}

/** Dynamic import that degrades to null instead of crashing when a concurrently
 *  developed module has not landed yet (CONTRACTS.md notes these are optional deps). */
async function tryImport(specifier) {
  try {
    return await import(specifier);
  } catch (err) {
    if (err && (err.code === 'ERR_MODULE_NOT_FOUND' || /Cannot find module/.test(String(err.message)))) {
      return null;
    }
    throw err;
  }
}

export async function buildDeps({ store, audit }) {
  const [recon_a, cutover, mapping, batch, worker, recon_c] = await Promise.all([
    tryImport('../core/recon_a.js'),
    tryImport('../core/cutover.js'),
    tryImport('../core/mapping.js'),
    tryImport('../core/batch.js'),
    tryImport('../worker/index.js'),
    tryImport('../core/recon_c.js'),
  ]);

  const booksConfig = loadBooksConfig();
  let books = null;
  try {
    books = createBooksClient({ driver: booksConfig.driver, config: booksConfig, store, audit });
  } catch (err) {
    log('error', 'books_client_init_failed', { error: String(err?.message ?? err) });
  }

  return { recon_a, cutover, mapping, batch, worker, recon_c, books };
}

async function main() {
  const store = await openStore({ adapter: process.env.STORE_ADAPTER ?? 'sqlite', path: process.env.SQLITE_PATH });
  const audit = createAudit(store);
  const users = loadUsers(process.env.USERS_CONFIG_PATH ?? './config/users.json');
  const deps = await buildDeps({ store, audit });

  const app = createApp({ store, audit, users, deps });
  const port = Number(process.env.PORT ?? 4100);
  app.listen(port, () => {
    log('info', 'server_listening', {
      port,
      storeAdapter: process.env.STORE_ADAPTER ?? 'sqlite',
      booksDriver: deps.books?.driver ?? 'unknown',
      users: users.length,
    });
  });
}

main().catch((err) => {
  log('error', 'server_failed_to_start', { error: String(err?.stack || err) });
  process.exitCode = 1;
});
