// Server entrypoint. See CONTRACTS.md §H. Loads env, opens the store, loads users,
// wires the real (or partially-available) core deps, and listens.
//
// Deployable-as-one-AppSail-service env wiring (task note): STORE_ADAPTER
// sqlite|catalyst, INBOX_ADAPTER local|bundled|workdrive, ARCHIVE_ADAPTER
// local|stratus|disabled. Users come from USERS_CONFIG_JSON (inline JSON, preferred in
// deployed envs where there is no writable/mountable config file) or else
// USERS_CONFIG_PATH. Port is X_ZOHO_CATALYST_LISTEN_PORT (AppSail) falling back to PORT.
// CATALYST_ENVIRONMENT is read from X_ZOHO_CATALYST_ENVIRONMENT (AppSail-provided) or
// CATALYST_ENVIRONMENT, defaulting to 'local' outside Catalyst.
import { existsSync, readFileSync } from 'node:fs';
import { openStore } from '../adapters/store/index.js';
import { openInbox } from '../adapters/inbox/index.js';
import { openArchive } from '../adapters/archive/index.js';
import { createAudit } from '../core/audit.js';
import { log } from '../core/log.js';
import { normalizeUsers } from './auth.js';
import { createApp } from './app.js';
import { createBooksClient, loadBooksConfig } from '../books/index.js';
import { createCatalystRuntime, makeRequestScopedStore, makeRequestScopedArchive } from './catalyst_runtime.js';

export class StartupConfigError extends Error {
  constructor(message) {
    super(message);
    this.code = 'STARTUP_CONFIG_INVALID';
  }
}

export function resolveEnvironment(env = process.env) {
  return env.X_ZOHO_CATALYST_ENVIRONMENT || env.CATALYST_ENVIRONMENT || 'local';
}

export function resolvePort(env = process.env) {
  return Number(env.X_ZOHO_CATALYST_LISTEN_PORT ?? env.PORT ?? 4100);
}

/**
 * Fail-closed startup check (task note): STORE_ADAPTER=catalyst (i.e. a real deployed
 * Catalyst environment) with ARCHIVE_ADAPTER=local would silently keep writing archived
 * files to the AppSail instance's local (ephemeral, write-restricted, per-instance) disk
 * instead of a real shared store — a migration pilot must never lose its immutable
 * archive trail that way. Refuses to start rather than silently falling back.
 */
export function assertDeployableConfig({ storeAdapter, archiveAdapter }) {
  if (storeAdapter === 'catalyst' && archiveAdapter === 'local') {
    throw new StartupConfigError(
      'STORE_ADAPTER=catalyst with ARCHIVE_ADAPTER=local is refused: a deployed Catalyst ' +
        'environment must not silently fall back to local disk for the archive. Set ' +
        'ARCHIVE_ADAPTER=stratus, or explicitly ARCHIVE_ADAPTER=disabled if this is a ' +
        'Development environment and Stratus has not been activated yet.'
    );
  }
}

/**
 * Users file shape (CONTRACTS.md §H): `{ users: [{ id, role, branches, token_sha256 }] }`
 * or a bare array of the same objects. Generated by a separate workstream
 * (config/users.json / config/users.example.json); never invent tokens here.
 */
function loadUsersFromPath(path) {
  if (!path || !existsSync(path)) {
    log('warn', 'users_config_not_found', { path });
    return [];
  }
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8'));
    const users = normalizeUsers(Array.isArray(raw) ? raw : raw.users ?? []);
    log('info', 'users_config_loaded', {
      source: 'path', path, count: users.length,
      bots: users.filter((u) => u.principal_type === 'bot').map((u) => u.id),
    });
    return users;
  } catch (err) {
    // Fail closed: a malformed or contradictory principal list (e.g. a bot declared as a
    // human operator) must stop the server rather than start with weaker authorization.
    log('error', 'users_config_invalid', { source: 'path', path, error: String(err?.message ?? err) });
    process.exit(1);
  }
}

/** USERS_CONFIG_JSON (inline JSON string) is preferred in deployed environments where
 * there is no mountable/writable config file — e.g. an AppSail environment variable
 * holding the whole users list. Falls back to USERS_CONFIG_PATH otherwise. */
export function loadUsers(env = process.env) {
  const inline = env.USERS_CONFIG_JSON;
  if (inline) {
    try {
      const raw = JSON.parse(inline);
      const users = normalizeUsers(Array.isArray(raw) ? raw : raw.users ?? []);
      log('info', 'users_config_loaded', { source: 'env:USERS_CONFIG_JSON', count: users.length });
      return users;
    } catch (err) {
      log('error', 'users_config_invalid', { source: 'env:USERS_CONFIG_JSON', error: String(err?.message ?? err) });
      process.exit(1);
    }
  }
  return loadUsersFromPath(env.USERS_CONFIG_PATH ?? './config/users.json');
}

/** Dynamic import that degrades to null instead of crashing when a concurrently
 *  developed module has not landed yet (CONTRACTS.md notes these are optional deps). */
async function tryImport(specifier) {
  try {
    return await import(specifier);
  } catch (err) {
    if (err && (err.code === 'ERR_MODULE_NOT_FOUND' || /Cannot find module/.test(String(err.message)))) {
      return null;
    }
    throw err;
  }
}

export async function buildDeps({ store, audit }) {
  const [recon_a, cutover, mapping, batch, worker, recon_c] = await Promise.all([
    tryImport('../core/recon_a.js'),
    tryImport('../core/cutover.js'),
    tryImport('../core/mapping.js'),
    tryImport('../core/batch.js'),
    tryImport('../worker/index.js'),
    tryImport('../core/recon_c.js'),
  ]);

  const booksConfig = loadBooksConfig();
  let books = null;
  try {
    books = createBooksClient({ driver: booksConfig.driver, config: booksConfig, store, audit });
  } catch (err) {
    log('error', 'books_client_init_failed', { error: String(err?.message ?? err) });
  }

  return { recon_a, cutover, mapping, batch, worker, recon_c, books };
}

async function main() {
  const storeAdapter = process.env.STORE_ADAPTER ?? 'sqlite';
  const archiveAdapter = process.env.ARCHIVE_ADAPTER ?? 'local';
  const inboxAdapter = process.env.INBOX_ADAPTER ?? 'local';
  const environment = resolveEnvironment();
  const devSeedEnabled = process.env.DEV_SEED_ENABLED === 'true';

  try {
    assertDeployableConfig({ storeAdapter, archiveAdapter });
  } catch (err) {
    log('error', 'startup_config_invalid', { error: err.message });
    process.exitCode = 1;
    return;
  }

  // The catalyst runtime is created unconditionally (cheap: it never touches the SDK
  // until a request actually needs it) so both the store and archive below can share one
  // AsyncLocalStorage-backed `currentApp()`.
  const runtime = createCatalystRuntime({});

  const store =
    storeAdapter === 'catalyst' ? makeRequestScopedStore() : await openStore({ adapter: storeAdapter, path: process.env.SQLITE_PATH });
  const audit = createAudit(store);
  const users = loadUsers();
  const deps = await buildDeps({ store, audit });

  let archive;
  if (archiveAdapter === 'stratus') {
    archive = makeRequestScopedArchive();
  } else if (archiveAdapter === 'disabled') {
    const mod = await import('../adapters/archive/disabled.js');
    archive = await mod.openArchive({ environment, audit });
  } else {
    archive = await openArchive({ adapter: archiveAdapter, root: process.env.ARCHIVE_LOCAL_PATH });
  }

  const inbox = await openInbox({ adapter: inboxAdapter, root: inboxAdapter === 'local' ? process.env.INBOX_LOCAL_PATH : undefined });

  const app = createApp({
    store,
    audit,
    users,
    deps,
    devDeps: { inbox, archive, client: deps.books },
    runtime: storeAdapter === 'catalyst' || archiveAdapter === 'stratus' ? runtime : undefined,
    environment,
    storeAdapter,
    archiveAdapter,
    inboxAdapter,
    devSeedEnabled,
  });

  const port = resolvePort();
  app.listen(port, () => {
    log('info', 'server_listening', {
      port,
      environment,
      storeAdapter,
      archiveAdapter,
      inboxAdapter,
      booksDriver: deps.books?.driver ?? 'unknown',
      users: users.length,
    });
  });
}

// Guarded like src/worker/index.js's main(): importing this module for its exported pure
// helpers (assertDeployableConfig, resolveEnvironment, resolvePort, loadUsers, buildDeps —
// see test/fail_closed.test.js) must never itself start a server.
const isMainModule = (() => {
  try {
    return import.meta.url === `file://${process.argv[1]?.replace(/\\/g, '/')}` || process.argv[1]?.endsWith('server/index.js') || process.argv[1]?.endsWith('server\\index.js');
  } catch {
    return false;
  }
})();

if (isMainModule) {
  main().catch((err) => {
    log('error', 'server_failed_to_start', { error: String(err?.stack || err) });
    process.exitCode = 1;
  });
}
